# health endpoint testen
GET http://localhost:2567/health

###

# alle Räume abrufen
GET http://localhost:2567/getRooms

###

# neuen Raum erstellen
POST http://localhost:2567/createRoom
Content-Type: application/json

{
  "width": 5,
  "height": 5,
  "mineCount": 3,
  "seed": 123
}
