/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GameSelectRouteImport } from './routes/game-select'
import { Route as RoomIdRouteImport } from './routes/$roomId'
import { Route as IndexRouteImport } from './routes/index'

const GameSelectRoute = GameSelectRouteImport.update({
  id: '/game-select',
  path: '/game-select',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomIdRoute = RoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$roomId': typeof RoomIdRoute
  '/game-select': typeof GameSelectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$roomId': typeof RoomIdRoute
  '/game-select': typeof GameSelectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$roomId': typeof RoomIdRoute
  '/game-select': typeof GameSelectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$roomId' | '/game-select'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$roomId' | '/game-select'
  id: '__root__' | '/' | '/$roomId' | '/game-select'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoomIdRoute: typeof RoomIdRoute
  GameSelectRoute: typeof GameSelectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/game-select': {
      id: '/game-select'
      path: '/game-select'
      fullPath: '/game-select'
      preLoaderRoute: typeof GameSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$roomId': {
      id: '/$roomId'
      path: '/$roomId'
      fullPath: '/$roomId'
      preLoaderRoute: typeof RoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoomIdRoute: RoomIdRoute,
  GameSelectRoute: GameSelectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
